

// we can create rulename here and define roles to access that 
export default {
  // User management
  CREATE_USER_UNDER_PARENT: [ 'OWNER', 'COMPANY', 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   GET_ALL_USERS: ['OWNER', 'COMPANY', 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   UPDATE_USER_PASSWORD: ['OWNER', 'COMPANY', 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],

  // Wallet operations
//   CREDIT_BALANCE: ['OWNER', 'COMPANY' , 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   DEBIT_BALANCE: ['OWNER', 'COMPANY' , 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   ADD_CASH: ['OWNER', 'COMPANY' , 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   SUBTRACT_CASH: ['OWNER', 'COMPANY' , 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   ADD_CREDIT: ['OWNER', 'COMPANY', 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   SUBTRACT_CREDIT: ['OWNER', 'COMPANY', 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],

  // Reports or data views
//   VIEW_USER_DETAILS: ['OWNER', 'COMPANY', 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],
//   VIEW_TRANSACTIONS: ['OWNER', 'COMPANY', 'SUPERADMIN', 'ADMIN', 'SUPERMASTER', 'MASTER'],

  // Default fallback
//   DEFAULT: ['OWNER', 'COMPANY',],
};
