
const allTablesData = {
  success: true,
  msg: "Success",
  status: 200,
  data: {
    t1: [
      {
        cid: 4,
        gid: 35,
        gmid: "ourroullete",
        gname: "Unique Roulette",
        gtid: 0,
        imgpath: "ourroullete.jpg",
        srno: 797,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "superover3",
        gname: "Mini Superover",
        gtid: 0,
        imgpath: "superover3.jpg",
        srno: 798,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "goal",
        gname: "Goal",
        gtid: 0,
        imgpath: "goal.jpg",
        srno: 799,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "ab4",
        gname: "ANDAR BAHAR 150 cards",
        gtid: 0,
        imgpath: "ab4.jpg",
        srno: 800,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "lucky15",
        gname: "Lucky 15",
        gtid: 0,
        imgpath: "lucky15.jpg",
        srno: 801,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "superover2",
        gname: "Super Over2",
        gtid: 0,
        imgpath: "superover2.jpg",
        srno: 802,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen41",
        gname: "Queen Top Open Teenpatti",
        gtid: 0,
        imgpath: "teen41.jpg",
        srno: 803,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen42",
        gname: "Jack Top Open Teenpatti",
        gtid: 0,
        imgpath: "teen42.jpg",
        srno: 804,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "sicbo2",
        gname: "Sic Bo2",
        gtid: 0,
        imgpath: "sicbo2.jpg",
        srno: 806,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen33",
        gname: "Instant Teenpatti 3.0",
        gtid: 0,
        imgpath: "teen33.jpg",
        srno: 809,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "sicbo",
        gname: "Sic Bo",
        gtid: 0,
        imgpath: "sicbo.jpg",
        srno: 810,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "ballbyball",
        gname: "Ball by Ball",
        gtid: 0,
        imgpath: "ballbyball.jpg",
        srno: 811,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen32",
        gname: "Instant Teenpatti 2.0",
        gtid: 0,
        imgpath: "teen32.jpg",
        srno: 812,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen",
        gname: "Teenpatti 1-day",
        gtid: 0,
        imgpath: "teen.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen20",
        gname: "20-20 Teenpatti",
        gtid: 0,
        imgpath: "teen20.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen9",
        gname: "Teenpatti Test",
        gtid: 0,
        imgpath: "teen9.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen8",
        gname: "Teenpatti Open",
        gtid: 0,
        imgpath: "teen8.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "poker",
        gname: "Poker 1-Day",
        gtid: 0,
        imgpath: "poker.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "poker20",
        gname: "20-20 Poker",
        gtid: 0,
        imgpath: "poker20.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "poker6",
        gname: "Poker 6 Players",
        gtid: 0,
        imgpath: "poker6.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "baccarat",
        gname: "Baccarat",
        gtid: 0,
        imgpath: "baccarat.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "baccarat2",
        gname: "Baccarat 2",
        gtid: 0,
        imgpath: "baccarat2.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "dt20",
        gname: "20-20 Dragon Tiger",
        gtid: 0,
        imgpath: "dt20.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "dt6",
        gname: "1 Day Dragon Tiger",
        gtid: 0,
        imgpath: "dt6.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "dtl20",
        gname: "20-20 D T L",
        gtid: 0,
        imgpath: "dtl20.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "dt202",
        gname: "20-20 Dragon Tiger 2",
        gtid: 0,
        imgpath: "dt202.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "card32",
        gname: "32 Cards A",
        gtid: 0,
        imgpath: "card32.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "card32eu",
        gname: "32 Cards B",
        gtid: 0,
        imgpath: "card32eu.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "ab20",
        gname: "Andar Bahar",
        gtid: 0,
        imgpath: "ab20.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "abj",
        gname: "Andar Bahar 2",
        gtid: 0,
        imgpath: "abj.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "lucky7",
        gname: "Lucky 7 - A",
        gtid: 0,
        imgpath: "lucky7.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "lucky7eu",
        gname: "Lucky 7 - B",
        gtid: 0,
        imgpath: "lucky7eu.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "3cardj",
        gname: "3 Cards Judgement",
        gtid: 0,
        imgpath: "3cardj.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "war",
        gname: "Casino War",
        gtid: 0,
        imgpath: "war.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "worli",
        gname: "Worli Matka",
        gtid: 0,
        imgpath: "worli.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "worli2",
        gname: "Instant Worli",
        gtid: 0,
        imgpath: "worli2.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "aaa",
        gname: "Amar Akbar Anthony",
        gtid: 0,
        imgpath: "aaa.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "btable",
        gname: "Bollywood Casino",
        gtid: 0,
        imgpath: "btable.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "lottcard",
        gname: "Lottery",
        gtid: 0,
        imgpath: "lottcard.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "cricketv3",
        gname: "5Five Cricket",
        gtid: 0,
        imgpath: "cricketv3.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "cmatch20",
        gname: "Cricket Match 20-20",
        gtid: 0,
        imgpath: "cmatch20.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "cmeter",
        gname: "Casino Meter",
        gtid: 0,
        imgpath: "cmeter.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen6",
        gname: "Teenpatti - 2.0",
        gtid: 0,
        imgpath: "teen6.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "queen",
        gname: "Queen",
        gtid: 0,
        imgpath: "queen.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "race20",
        gname: "Race20",
        gtid: 0,
        imgpath: "race20.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "lucky7eu2",
        gname: "Lucky 7 - C",
        gtid: 0,
        imgpath: "lucky7eu2.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "superover",
        gname: "Super Over",
        gtid: 0,
        imgpath: "superover.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "trap",
        gname: "The Trap",
        gtid: 0,
        imgpath: "trap.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "patti2",
        gname: "2 Cards Teenpatti",
        gtid: 0,
        imgpath: "patti2.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teensin",
        gname: "29Card Baccarat",
        gtid: 0,
        imgpath: "teensin.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teenmuf",
        gname: "Muflis Teenpatti",
        gtid: 0,
        imgpath: "teenmuf.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "race17",
        gname: "Race To 17",
        gtid: 0,
        imgpath: "race17.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
      {
        cid: 4,
        gid: 35,
        gmid: "teen20b",
        gname: "20-20 Teenpatti B",
        gtid: 0,
        imgpath: "teen20b.jpg",
        srno: 985,
        tabno: 6,
        isframe: 0,
        tid: 0,
      },
    ],
  },
}

export default allTablesData

